In [20]:
import duckdb
from logica.common import logica_lib

In [21]:
db_path = "../data/madrid.duckdb"
connection = duckdb.connect(db_path)

## Global segregation

In [24]:
Segregation = logica_lib.RunPredicateToPandas('segregation.l',
                                                       'Segregation',
                                                       connection=connection)
Segregation

,segregation_value,school_code,school_name,school_type_desc_abbr,minority_school_students,total_school_students
0,-0.003499,28015471,SAN AGUSTIN,CPR INF-PRI-SEC,0.0,154.0
1,-0.003249,28077865,ALFREDO DI STEFANO,CP INF-PRI-SEC,0.0,143.0
2,-0.003158,28038562,ALKOR,CPR INF-PRI-SEC,0.0,139.0
3,-0.002999,28013371,NUESTRA SEÑORA DEL RECUERDO,CPR INF-PRI-SEC,0.0,132.0
4,-0.002999,28065747,COLEGIO VALDEFUENTES,CPR INF-PRI-SEC,0.0,132.0
...,...,...,...,...,...,...
1243,0.007210,28030344,MANUEL AZAÑA,CP INF-PRI,6.0,14.0
1244,0.007533,28005933,EDUARDO ROJO,CP INF-PRI,7.0,55.0
1245,0.007806,28031051,MIGUEL SERVET,CP INF-PRI,7.0,43.0
1246,0.009129,28067586,ROSA MONTERO,CP INF-PRI,8.0,40.0
1247,0.012070,28009801,SANTO ANGEL DE LA GUARDA,CPR INF-PRI-SEC,10.0,21.0

In [26]:
MunicipalitySegregation = logica_lib.RunPredicateToPandas('segregation.l',
                                              'MunicipalitySegregation',
                                              connection=connection)
MunicipalitySegregation

,segregation_value,municipality,minority_municipality_students,total_municipality_students
0,-0.014565,Las Rozas de Madrid,0.0,641.0
1,-0.013847,Alcorcón,12.0,1272.0
2,-0.012758,Rivas-Vaciamadrid,7.0,948.0
3,-0.008925,Boadilla del Monte,1.0,448.0
4,-0.008466,Colmenar Viejo,2.0,483.0
...,...,...,...,...
130,0.010967,Alcalá de Henares,35.0,1450.0
131,0.013492,Leganés,31.0,1118.0
132,0.015169,Aranjuez,21.0,492.0
133,0.026766,Parla,41.0,1086.0
134,0.065153,Madrid,400.0,19220.0

## Local segregation

In [25]:
MunicipalSegregation = logica_lib.RunPredicateToPandas('segregation.l',
                                                       'MunicipalSegregation',
                                                       connection=connection)
MunicipalSegregation

,segregation_value,school_code,school_name,school_type_desc_abbr,municipality,minority_school_students,total_school_students
0,-0.117037,28072958,GREENWICH SCHOOL,CPR INF-PRI-SEC,Alcobendas,0.0,79.0
1,-0.109277,28038562,ALKOR,CPR INF-PRI-SEC,Alcorcón,0.0,139.0
2,-0.103659,28067859,COLEGIO LITTERATOR,CPR INF-PRI-SEC,Aranjuez,0.0,51.0
3,-0.098522,28070721,BEETHOVEN,CP INF-PRI,Torrejón de Ardoz,0.0,100.0
4,-0.088966,28067343,GSD ALCALA,CPR INF-PRI-SEC,Alcalá de Henares,0.0,129.0
...,...,...,...,...,...,...,...
842,0.138067,28002981,SAGRADO CORAZON,CP INF-PRI,Getafe,4.0,32.0
843,0.154088,28033679,MIGUEL DE CERVANTES,CP INF-PRI-SEC,Alcorcón,2.0,16.0
844,0.158290,28067586,ROSA MONTERO,CP INF-PRI,Parla,8.0,40.0
845,0.161773,28030344,MANUEL AZAÑA,CP INF-PRI,Alcalá de Henares,6.0,14.0
846,0.208547,28032353,MIGUEL HERNANDEZ,CP INF-PRI,Alcobendas,3.0,15.0

## NearbyOppositeSchools

In [9]:
NearbyOppositeSchools = logica_lib.RunPredicateToPandas('segregation.l',
                                     'NearbyOppositeSchools',
                                     connection=connection)
NearbyOppositeSchools

,school_code1,school_name1,surplus,school_code2,school_name2,shortage,distance,municipality,minority_municipality_students
0,28067586,CP INF-PRI ROSA MONTERO,6.489871,28070986,CP INF-PRI MADRE TERESA DE CALCUTA,1.322284,331.049845,Parla,41.0
1,28067586,CP INF-PRI ROSA MONTERO,6.489871,28075637,CPR INF-PRI-SEC COLEGIO JUAN PABLO II,2.718232,484.905145,Parla,41.0
2,28010862,CP INF-PRI MANUEL NUÑEZ DE ARENAS,4.542144,28045566,CPR INF-PRI-SEC GSD VALLECAS,2.039542,453.745523,Madrid,400.0
3,28045098,CP INF-PRI VALDEBERNARDO,3.959417,28049857,CPR INF-PRI-SEC EL VALLE,1.165453,112.605506,Madrid,400.0
4,28002981,CP INF-PRI SAGRADO CORAZON,3.451679,28003250,CPR INF-PRI-SEC LA INMACULADA-PADRES ESCOLAPIOS,1.353667,134.033578,Getafe,25.0
5,28049377,CP INF-PRI MARIA MOLINER,3.375650,28064202,CPR INF-PRI-SEC COLEGIO INTERNACIONAL J.H. NEWMAN,1.810614,313.588903,Madrid,400.0
6,28025981,CP INF-PRI VIRGEN DEL CERRO,3.167534,28011908,CPR INF-PRI-SEC TAJAMAR,1.040583,124.739729,Madrid,400.0
7,28026547,CP INF-PRI GINER DE LOS RIOS,2.625390,28045566,CPR INF-PRI-SEC GSD VALLECAS,2.039542,431.296882,Madrid,400.0
8,28003316,CP INF-PRI SAN JOSE DE CALASANZ,2.623029,28003250,CPR INF-PRI-SEC LA INMACULADA-PADRES ESCOLAPIOS,1.353667,422.755248,Getafe,25.0
9,28043031,CP INF-PRI GINER DE LOS RIOS,2.546041,28041536,CPR INF-PRI-SEC TORRENTE BALLESTER,1.547882,161.418710,Parla,41.0
10,28043031,CP INF-PRI GINER DE LOS RIOS,2.546041,28063881,CP INF-PRI LOS LAGOS,1.396869,345.365024,Parla,41.0
11,28031464,CP INF-PRI JOSE MARIA DE PEREDA,2.389982,28003845,CP INF-PRI ORTEGA Y GASSET,1.025939,221.794950,Leganés,31.0
12,28006172,CP INF-PRI REPUBLICA DE ECUADOR,2.084287,28007191,CPR INF-PRI-SEC NAZARET-OPORTO,1.373569,388.902301,Madrid,400.0
13,28001551,CP INF-PRI VICENTE ALEIXANDRE,2.060976,28001514,CPR INF-PRI-SEC SAGRADA FAMILIA,1.365854,319.452657,Aranjuez,21.0
14,28037168,CP INF-PRI LUIS VIVES,2.034483,28028738,CP INF-PRI BEATRIZ GALINDO,1.448276,242.441746,Alcalá de Henares,35.0
15,28003742,CPR INF-PRI-SEC EL SALVADOR,1.946333,28003675,CPR INF-PRI-SEC LICEO SAN PABLO,1.025939,294.363721,Leganés,31.0
16,28005881,CP INF-PRI MENENDEZ Y PELAYO,1.813736,28012640,CPR INF-PRI-SEC SALESIANOS ATOCHA,1.290323,459.200392,Madrid,400.0
17,28028209,CP INF-PRI PARDO BAZAN,1.584079,28028222,CP INF-PRI PIO BAROJA,1.109123,149.335193,Leganés,31.0
18,28006068,CP INF-PRI PINAR DEL REY,1.375650,28019270,CPR INF-PRI-SEC LA INMACULADA,1.165453,284.344861,Madrid,400.0
19,28005039,CP INF-PRI ANTONIO MACHADO,1.250780,28011261,CPR INF-PRI-SEC AMOROS,1.706556,265.414770,Madrid,400.0
20,28023546,CP INF-PRI VIRGEN DEL CARMEN,1.244936,28041536,CPR INF-PRI-SEC TORRENTE BALLESTER,1.547882,291.743038,Parla,41.0
21,28023546,CP INF-PRI VIRGEN DEL CARMEN,1.244936,28063881,CP INF-PRI LOS LAGOS,1.396869,357.694003,Parla,41.0
22,28029597,CP INF-PRI SAN FERNANDO,1.231707,28001605,CPR INF-PRI-SEC LOYOLA,1.329268,337.397392,Aranjuez,21.0
23,28029597,CP INF-PRI SAN FERNANDO,1.231707,28029603,CP INF-PRI SANTA TERESA DE JESUS,1.195122,471.644994,Aranjuez,21.0
24,28005568,CP INF-PRI ISAAC PERAL,1.209157,28007191,CPR INF-PRI-SEC NAZARET-OPORTO,1.373569,493.705378,Madrid,400.0
25,28037636,CP INF-PRI LEON FELIPE,1.168157,28003675,CPR INF-PRI-SEC LICEO SAN PABLO,1.025939,276.378364,Leganés,31.0
26,28037636,CP INF-PRI LEON FELIPE,1.168157,28003845,CP INF-PRI ORTEGA Y GASSET,1.025939,486.251992,Leganés,31.0
27,28014363,CPR INF-PRI-SEC SANTA CATALINA DE SENA,1.105099,28008909,CPR INF-PRI-SEC SAGRADO CORAZON,1.248699,175.513532,Madrid,400.0
28,28031440,CP INF-PRI FRANCISCO DE QUEVEDO,1.034483,28028738,CP INF-PRI BEATRIZ GALINDO,1.448276,394.182699,Alcalá de Henares,35.0

In [19]:
connection.close()